// Generated by tools/generate_cl_symbols.py from CL/cl.h and CL/cl_gl.h.
// Keep callback types, C linkage and CL_API_CALL exactly as declared there.
#include "cl_symbols.h"

#include <string>
#include <vector>

namespace au {
namespace gpu {

CLSymbols& CLSymbols::instance()
{
    static CLSymbols instance;
    return instance;
}

bool CLSymbols::isLoaded() noexcept
{
    try {
        return instance().mLoaded;
    } catch (...) {
        return false;
    }
}

CLSymbols::CLSymbols()
{
    try {
        const std::vector<std::string> paths = {
#if AU_OS_WINDOWS
            "OpenCL.dll", "OpenCL64.dll", "OpenCL32.dll"
#elif AU_OS_APPLE
            "/System/Library/Frameworks/OpenCL.framework/OpenCL"
#elif AU_OS_ANDROID
            "libOpenCL.so",
            "/vendor/lib64/libOpenCL.so", "/system/vendor/lib64/libOpenCL.so", "/system/lib64/libOpenCL.so",
            "/vendor/lib/libOpenCL.so", "/system/vendor/lib/libOpenCL.so", "/system/lib/libOpenCL.so"
#elif AU_OS_LINUX
            "libOpenCL.so.1", "libOpenCL.so",
            "/usr/lib/x86_64-linux-gnu/libOpenCL.so.1", "/usr/lib/x86_64-linux-gnu/libOpenCL.so",
            "/usr/lib/libOpenCL.so.1", "/usr/lib/libOpenCL.so", "/usr/lib64/libOpenCL.so.1", "/usr/lib64/libOpenCL.so"
#else
            "libOpenCL.so", "OpenCL.dll"
#endif
        };
        mLoaded = (mLib.load(paths) == sys::XDLib::kSuccess);
    } catch (...) {
        // Path allocation/loading failed. Calls report unavailable OpenCL
        // through their return values, rather than terminating the process.
        mLoaded = false;
    }
}

} // namespace gpu
} // namespace au

// Function-local static initialization publishes each pointer once, safely
// across threads. A missing pointer is cached too. Steady-state dispatch has
// no name lookup, container allocation or XDLib mutex acquisition.
#define CL_RESOLVE(name) \
    static const auto fp = ::au::gpu::CLSymbols::get<decltype(::name)>(#name)

namespace {
#ifdef CL_PLATFORM_NOT_FOUND_KHR
constexpr cl_int kPlatformNotFound = CL_PLATFORM_NOT_FOUND_KHR;
#else
// Apple SDK headers omit the cl_khr_icd error macro; Khronos assigns -1001.
constexpr cl_int kPlatformNotFound = -1001;
#endif
} // anonymous namespace

// Unavailable core entry points return CL_INVALID_OPERATION. Handle/mapping
// creators also set errcode_ret when supplied. Extension queries return null;
// clSVMFree has no error return and becomes a no-op if its symbol is absent.
extern "C" {

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clGetPlatformIDs(
    cl_uint num_entries,
    cl_platform_id * platforms,
    cl_uint * num_platforms)
{
    CL_RESOLVE(clGetPlatformIDs);
    if (fp == nullptr) {
        if (num_platforms != nullptr) {
            *num_platforms = 0;
        }
        return kPlatformNotFound;
    }
    return fp(num_entries, platforms, num_platforms);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clGetPlatformInfo(
    cl_platform_id platform,
    cl_platform_info param_name,
    size_t param_value_size,
    void * param_value,
    size_t * param_value_size_ret)
{
    CL_RESOLVE(clGetPlatformInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(platform, param_name, param_value_size, param_value, param_value_size_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clGetDeviceIDs(
    cl_platform_id platform,
    cl_device_type device_type,
    cl_uint num_entries,
    cl_device_id * devices,
    cl_uint * num_devices)
{
    CL_RESOLVE(clGetDeviceIDs);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(platform, device_type, num_entries, devices, num_devices);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clGetDeviceInfo(
    cl_device_id device,
    cl_device_info param_name,
    size_t param_value_size,
    void * param_value,
    size_t * param_value_size_ret)
{
    CL_RESOLVE(clGetDeviceInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(device, param_name, param_value_size, param_value, param_value_size_ret);
}
#endif

#if defined(CL_VERSION_1_2)
cl_int CL_API_CALL clCreateSubDevices(
    cl_device_id in_device,
    const cl_device_partition_property * properties,
    cl_uint num_devices,
    cl_device_id * out_devices,
    cl_uint * num_devices_ret)
{
    CL_RESOLVE(clCreateSubDevices);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(in_device, properties, num_devices, out_devices, num_devices_ret);
}
#endif

#if defined(CL_VERSION_1_2)
cl_int CL_API_CALL clRetainDevice(
    cl_device_id device)
{
    CL_RESOLVE(clRetainDevice);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(device);
}
#endif

#if defined(CL_VERSION_1_2)
cl_int CL_API_CALL clReleaseDevice(
    cl_device_id device)
{
    CL_RESOLVE(clReleaseDevice);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(device);
}
#endif

#if defined(CL_VERSION_2_1)
cl_int CL_API_CALL clSetDefaultDeviceCommandQueue(
    cl_context context,
    cl_device_id device,
    cl_command_queue command_queue)
{
    CL_RESOLVE(clSetDefaultDeviceCommandQueue);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(context, device, command_queue);
}
#endif

#if defined(CL_VERSION_2_1)
cl_int CL_API_CALL clGetDeviceAndHostTimer(
    cl_device_id device,
    cl_ulong* device_timestamp,
    cl_ulong* host_timestamp)
{
    CL_RESOLVE(clGetDeviceAndHostTimer);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(device, device_timestamp, host_timestamp);
}
#endif

#if defined(CL_VERSION_2_1)
cl_int CL_API_CALL clGetHostTimer(
    cl_device_id device,
    cl_ulong * host_timestamp)
{
    CL_RESOLVE(clGetHostTimer);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(device, host_timestamp);
}
#endif

#if defined(CL_VERSION_1_0)
cl_context CL_API_CALL clCreateContext(
    const cl_context_properties * properties,
    cl_uint num_devices,
    const cl_device_id * devices,
    void (CL_CALLBACK * pfn_notify)(const char * errinfo, const void * private_info, size_t cb, void * user_data),
    void * user_data,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreateContext);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(properties, num_devices, devices, pfn_notify, user_data, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_context CL_API_CALL clCreateContextFromType(
    const cl_context_properties * properties,
    cl_device_type device_type,
    void (CL_CALLBACK * pfn_notify)(const char * errinfo, const void * private_info, size_t cb, void * user_data),
    void * user_data,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreateContextFromType);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(properties, device_type, pfn_notify, user_data, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clRetainContext(
    cl_context context)
{
    CL_RESOLVE(clRetainContext);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(context);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clReleaseContext(
    cl_context context)
{
    CL_RESOLVE(clReleaseContext);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(context);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clGetContextInfo(
    cl_context context,
    cl_context_info param_name,
    size_t param_value_size,
    void * param_value,
    size_t * param_value_size_ret)
{
    CL_RESOLVE(clGetContextInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(context, param_name, param_value_size, param_value, param_value_size_ret);
}
#endif

#if defined(CL_VERSION_3_0)
cl_int CL_API_CALL clSetContextDestructorCallback(
    cl_context context,
    void (CL_CALLBACK* pfn_notify)(cl_context context, void* user_data),
    void* user_data)
{
    CL_RESOLVE(clSetContextDestructorCallback);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(context, pfn_notify, user_data);
}
#endif

#if defined(CL_VERSION_2_0)
cl_command_queue CL_API_CALL clCreateCommandQueueWithProperties(
    cl_context context,
    cl_device_id device,
    const cl_queue_properties * properties,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreateCommandQueueWithProperties);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, device, properties, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clRetainCommandQueue(
    cl_command_queue command_queue)
{
    CL_RESOLVE(clRetainCommandQueue);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clReleaseCommandQueue(
    cl_command_queue command_queue)
{
    CL_RESOLVE(clReleaseCommandQueue);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clGetCommandQueueInfo(
    cl_command_queue command_queue,
    cl_command_queue_info param_name,
    size_t param_value_size,
    void * param_value,
    size_t * param_value_size_ret)
{
    CL_RESOLVE(clGetCommandQueueInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, param_name, param_value_size, param_value, param_value_size_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_mem CL_API_CALL clCreateBuffer(
    cl_context context,
    cl_mem_flags flags,
    size_t size,
    void * host_ptr,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreateBuffer);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, flags, size, host_ptr, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_1)
cl_mem CL_API_CALL clCreateSubBuffer(
    cl_mem buffer,
    cl_mem_flags flags,
    cl_buffer_create_type buffer_create_type,
    const void * buffer_create_info,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreateSubBuffer);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(buffer, flags, buffer_create_type, buffer_create_info, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_2)
cl_mem CL_API_CALL clCreateImage(
    cl_context context,
    cl_mem_flags flags,
    const cl_image_format * image_format,
    const cl_image_desc * image_desc,
    void * host_ptr,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreateImage);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, flags, image_format, image_desc, host_ptr, errcode_ret);
}
#endif

#if defined(CL_VERSION_2_0)
cl_mem CL_API_CALL clCreatePipe(
    cl_context context,
    cl_mem_flags flags,
    cl_uint pipe_packet_size,
    cl_uint pipe_max_packets,
    const cl_pipe_properties * properties,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreatePipe);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, flags, pipe_packet_size, pipe_max_packets, properties, errcode_ret);
}
#endif

#if defined(CL_VERSION_3_0)
cl_mem CL_API_CALL clCreateBufferWithProperties(
    cl_context context,
    const cl_mem_properties * properties,
    cl_mem_flags flags,
    size_t size,
    void * host_ptr,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreateBufferWithProperties);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, properties, flags, size, host_ptr, errcode_ret);
}
#endif

#if defined(CL_VERSION_3_0)
cl_mem CL_API_CALL clCreateImageWithProperties(
    cl_context context,
    const cl_mem_properties * properties,
    cl_mem_flags flags,
    const cl_image_format * image_format,
    const cl_image_desc * image_desc,
    void * host_ptr,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreateImageWithProperties);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, properties, flags, image_format, image_desc, host_ptr, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clRetainMemObject(
    cl_mem memobj)
{
    CL_RESOLVE(clRetainMemObject);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(memobj);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clReleaseMemObject(
    cl_mem memobj)
{
    CL_RESOLVE(clReleaseMemObject);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(memobj);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clGetSupportedImageFormats(
    cl_context context,
    cl_mem_flags flags,
    cl_mem_object_type image_type,
    cl_uint num_entries,
    cl_image_format * image_formats,
    cl_uint * num_image_formats)
{
    CL_RESOLVE(clGetSupportedImageFormats);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(context, flags, image_type, num_entries, image_formats, num_image_formats);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clGetMemObjectInfo(
    cl_mem memobj,
    cl_mem_info param_name,
    size_t param_value_size,
    void * param_value,
    size_t * param_value_size_ret)
{
    CL_RESOLVE(clGetMemObjectInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(memobj, param_name, param_value_size, param_value, param_value_size_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clGetImageInfo(
    cl_mem image,
    cl_image_info param_name,
    size_t param_value_size,
    void * param_value,
    size_t * param_value_size_ret)
{
    CL_RESOLVE(clGetImageInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(image, param_name, param_value_size, param_value, param_value_size_ret);
}
#endif

#if defined(CL_VERSION_2_0)
cl_int CL_API_CALL clGetPipeInfo(
    cl_mem pipe,
    cl_pipe_info param_name,
    size_t param_value_size,
    void * param_value,
    size_t * param_value_size_ret)
{
    CL_RESOLVE(clGetPipeInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(pipe, param_name, param_value_size, param_value, param_value_size_ret);
}
#endif

#if defined(CL_VERSION_1_1)
cl_int CL_API_CALL clSetMemObjectDestructorCallback(
    cl_mem memobj,
    void (CL_CALLBACK * pfn_notify)(cl_mem memobj, void * user_data),
    void * user_data)
{
    CL_RESOLVE(clSetMemObjectDestructorCallback);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(memobj, pfn_notify, user_data);
}
#endif

#if defined(CL_VERSION_2_0)
void * CL_API_CALL clSVMAlloc(
    cl_context context,
    cl_svm_mem_flags flags,
    size_t size,
    cl_uint alignment)
{
    CL_RESOLVE(clSVMAlloc);
    if (fp == nullptr) {
        return nullptr;
    }
    return fp(context, flags, size, alignment);
}
#endif

#if defined(CL_VERSION_2_0)
void CL_API_CALL clSVMFree(
    cl_context context,
    void * svm_pointer)
{
    CL_RESOLVE(clSVMFree);
    if (fp == nullptr) {
        return;
    }
    fp(context, svm_pointer);
}
#endif

#if defined(CL_VERSION_2_0)
cl_sampler CL_API_CALL clCreateSamplerWithProperties(
    cl_context context,
    const cl_sampler_properties * sampler_properties,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreateSamplerWithProperties);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, sampler_properties, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clRetainSampler(
    cl_sampler sampler)
{
    CL_RESOLVE(clRetainSampler);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(sampler);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clReleaseSampler(
    cl_sampler sampler)
{
    CL_RESOLVE(clReleaseSampler);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(sampler);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clGetSamplerInfo(
    cl_sampler sampler,
    cl_sampler_info param_name,
    size_t param_value_size,
    void * param_value,
    size_t * param_value_size_ret)
{
    CL_RESOLVE(clGetSamplerInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(sampler, param_name, param_value_size, param_value, param_value_size_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_program CL_API_CALL clCreateProgramWithSource(
    cl_context context,
    cl_uint count,
    const char ** strings,
    const size_t * lengths,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreateProgramWithSource);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, count, strings, lengths, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_program CL_API_CALL clCreateProgramWithBinary(
    cl_context context,
    cl_uint num_devices,
    const cl_device_id * device_list,
    const size_t * lengths,
    const unsigned char ** binaries,
    cl_int * binary_status,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreateProgramWithBinary);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, num_devices, device_list, lengths, binaries, binary_status, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_2)
cl_program CL_API_CALL clCreateProgramWithBuiltInKernels(
    cl_context context,
    cl_uint num_devices,
    const cl_device_id * device_list,
    const char * kernel_names,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreateProgramWithBuiltInKernels);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, num_devices, device_list, kernel_names, errcode_ret);
}
#endif

#if defined(CL_VERSION_2_1)
cl_program CL_API_CALL clCreateProgramWithIL(
    cl_context context,
    const void* il,
    size_t length,
    cl_int* errcode_ret)
{
    CL_RESOLVE(clCreateProgramWithIL);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, il, length, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clRetainProgram(
    cl_program program)
{
    CL_RESOLVE(clRetainProgram);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(program);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clReleaseProgram(
    cl_program program)
{
    CL_RESOLVE(clReleaseProgram);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(program);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clBuildProgram(
    cl_program program,
    cl_uint num_devices,
    const cl_device_id * device_list,
    const char * options,
    void (CL_CALLBACK * pfn_notify)(cl_program program, void * user_data),
    void * user_data)
{
    CL_RESOLVE(clBuildProgram);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(program, num_devices, device_list, options, pfn_notify, user_data);
}
#endif

#if defined(CL_VERSION_1_2)
cl_int CL_API_CALL clCompileProgram(
    cl_program program,
    cl_uint num_devices,
    const cl_device_id * device_list,
    const char * options,
    cl_uint num_input_headers,
    const cl_program * input_headers,
    const char ** header_include_names,
    void (CL_CALLBACK * pfn_notify)(cl_program program, void * user_data),
    void * user_data)
{
    CL_RESOLVE(clCompileProgram);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(program, num_devices, device_list, options, num_input_headers, input_headers, header_include_names, pfn_notify, user_data);
}
#endif

#if defined(CL_VERSION_1_2)
cl_program CL_API_CALL clLinkProgram(
    cl_context context,
    cl_uint num_devices,
    const cl_device_id * device_list,
    const char * options,
    cl_uint num_input_programs,
    const cl_program * input_programs,
    void (CL_CALLBACK * pfn_notify)(cl_program program, void * user_data),
    void * user_data,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clLinkProgram);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, num_devices, device_list, options, num_input_programs, input_programs, pfn_notify, user_data, errcode_ret);
}
#endif

#if defined(CL_VERSION_2_2)
cl_int CL_API_CALL clSetProgramReleaseCallback(
    cl_program program,
    void (CL_CALLBACK * pfn_notify)(cl_program program, void * user_data),
    void * user_data)
{
    CL_RESOLVE(clSetProgramReleaseCallback);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(program, pfn_notify, user_data);
}
#endif

#if defined(CL_VERSION_2_2)
cl_int CL_API_CALL clSetProgramSpecializationConstant(
    cl_program program,
    cl_uint spec_id,
    size_t spec_size,
    const void* spec_value)
{
    CL_RESOLVE(clSetProgramSpecializationConstant);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(program, spec_id, spec_size, spec_value);
}
#endif

#if defined(CL_VERSION_1_2)
cl_int CL_API_CALL clUnloadPlatformCompiler(
    cl_platform_id platform)
{
    CL_RESOLVE(clUnloadPlatformCompiler);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(platform);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clGetProgramInfo(
    cl_program program,
    cl_program_info param_name,
    size_t param_value_size,
    void * param_value,
    size_t * param_value_size_ret)
{
    CL_RESOLVE(clGetProgramInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(program, param_name, param_value_size, param_value, param_value_size_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clGetProgramBuildInfo(
    cl_program program,
    cl_device_id device,
    cl_program_build_info param_name,
    size_t param_value_size,
    void * param_value,
    size_t * param_value_size_ret)
{
    CL_RESOLVE(clGetProgramBuildInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(program, device, param_name, param_value_size, param_value, param_value_size_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_kernel CL_API_CALL clCreateKernel(
    cl_program program,
    const char * kernel_name,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreateKernel);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(program, kernel_name, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clCreateKernelsInProgram(
    cl_program program,
    cl_uint num_kernels,
    cl_kernel * kernels,
    cl_uint * num_kernels_ret)
{
    CL_RESOLVE(clCreateKernelsInProgram);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(program, num_kernels, kernels, num_kernels_ret);
}
#endif

#if defined(CL_VERSION_2_1)
cl_kernel CL_API_CALL clCloneKernel(
    cl_kernel source_kernel,
    cl_int* errcode_ret)
{
    CL_RESOLVE(clCloneKernel);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(source_kernel, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clRetainKernel(
    cl_kernel kernel)
{
    CL_RESOLVE(clRetainKernel);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(kernel);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clReleaseKernel(
    cl_kernel kernel)
{
    CL_RESOLVE(clReleaseKernel);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(kernel);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clSetKernelArg(
    cl_kernel kernel,
    cl_uint arg_index,
    size_t arg_size,
    const void * arg_value)
{
    CL_RESOLVE(clSetKernelArg);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(kernel, arg_index, arg_size, arg_value);
}
#endif

#if defined(CL_VERSION_2_0)
cl_int CL_API_CALL clSetKernelArgSVMPointer(
    cl_kernel kernel,
    cl_uint arg_index,
    const void * arg_value)
{
    CL_RESOLVE(clSetKernelArgSVMPointer);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(kernel, arg_index, arg_value);
}
#endif

#if defined(CL_VERSION_2_0)
cl_int CL_API_CALL clSetKernelExecInfo(
    cl_kernel kernel,
    cl_kernel_exec_info param_name,
    size_t param_value_size,
    const void * param_value)
{
    CL_RESOLVE(clSetKernelExecInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(kernel, param_name, param_value_size, param_value);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clGetKernelInfo(
    cl_kernel kernel,
    cl_kernel_info param_name,
    size_t param_value_size,
    void * param_value,
    size_t * param_value_size_ret)
{
    CL_RESOLVE(clGetKernelInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(kernel, param_name, param_value_size, param_value, param_value_size_ret);
}
#endif

#if defined(CL_VERSION_1_2)
cl_int CL_API_CALL clGetKernelArgInfo(
    cl_kernel kernel,
    cl_uint arg_indx,
    cl_kernel_arg_info param_name,
    size_t param_value_size,
    void * param_value,
    size_t * param_value_size_ret)
{
    CL_RESOLVE(clGetKernelArgInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(kernel, arg_indx, param_name, param_value_size, param_value, param_value_size_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clGetKernelWorkGroupInfo(
    cl_kernel kernel,
    cl_device_id device,
    cl_kernel_work_group_info param_name,
    size_t param_value_size,
    void * param_value,
    size_t * param_value_size_ret)
{
    CL_RESOLVE(clGetKernelWorkGroupInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(kernel, device, param_name, param_value_size, param_value, param_value_size_ret);
}
#endif

#if defined(CL_VERSION_2_1)
cl_int CL_API_CALL clGetKernelSubGroupInfo(
    cl_kernel kernel,
    cl_device_id device,
    cl_kernel_sub_group_info param_name,
    size_t input_value_size,
    const void* input_value,
    size_t param_value_size,
    void* param_value,
    size_t* param_value_size_ret)
{
    CL_RESOLVE(clGetKernelSubGroupInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(kernel, device, param_name, input_value_size, input_value, param_value_size, param_value, param_value_size_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clWaitForEvents(
    cl_uint num_events,
    const cl_event * event_list)
{
    CL_RESOLVE(clWaitForEvents);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(num_events, event_list);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clGetEventInfo(
    cl_event event,
    cl_event_info param_name,
    size_t param_value_size,
    void * param_value,
    size_t * param_value_size_ret)
{
    CL_RESOLVE(clGetEventInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(event, param_name, param_value_size, param_value, param_value_size_ret);
}
#endif

#if defined(CL_VERSION_1_1)
cl_event CL_API_CALL clCreateUserEvent(
    cl_context context,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreateUserEvent);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clRetainEvent(
    cl_event event)
{
    CL_RESOLVE(clRetainEvent);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(event);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clReleaseEvent(
    cl_event event)
{
    CL_RESOLVE(clReleaseEvent);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(event);
}
#endif

#if defined(CL_VERSION_1_1)
cl_int CL_API_CALL clSetUserEventStatus(
    cl_event event,
    cl_int execution_status)
{
    CL_RESOLVE(clSetUserEventStatus);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(event, execution_status);
}
#endif

#if defined(CL_VERSION_1_1)
cl_int CL_API_CALL clSetEventCallback(
    cl_event event,
    cl_int command_exec_callback_type,
    void (CL_CALLBACK * pfn_notify)(cl_event event, cl_int event_command_status, void * user_data),
    void * user_data)
{
    CL_RESOLVE(clSetEventCallback);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(event, command_exec_callback_type, pfn_notify, user_data);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clGetEventProfilingInfo(
    cl_event event,
    cl_profiling_info param_name,
    size_t param_value_size,
    void * param_value,
    size_t * param_value_size_ret)
{
    CL_RESOLVE(clGetEventProfilingInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(event, param_name, param_value_size, param_value, param_value_size_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clFlush(
    cl_command_queue command_queue)
{
    CL_RESOLVE(clFlush);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clFinish(
    cl_command_queue command_queue)
{
    CL_RESOLVE(clFinish);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clEnqueueReadBuffer(
    cl_command_queue command_queue,
    cl_mem buffer,
    cl_bool blocking_read,
    size_t offset,
    size_t size,
    void * ptr,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueReadBuffer);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, buffer, blocking_read, offset, size, ptr, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_1)
cl_int CL_API_CALL clEnqueueReadBufferRect(
    cl_command_queue command_queue,
    cl_mem buffer,
    cl_bool blocking_read,
    const size_t * buffer_origin,
    const size_t * host_origin,
    const size_t * region,
    size_t buffer_row_pitch,
    size_t buffer_slice_pitch,
    size_t host_row_pitch,
    size_t host_slice_pitch,
    void * ptr,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueReadBufferRect);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, buffer, blocking_read, buffer_origin, host_origin, region, buffer_row_pitch, buffer_slice_pitch, host_row_pitch, host_slice_pitch, ptr, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clEnqueueWriteBuffer(
    cl_command_queue command_queue,
    cl_mem buffer,
    cl_bool blocking_write,
    size_t offset,
    size_t size,
    const void * ptr,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueWriteBuffer);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, buffer, blocking_write, offset, size, ptr, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_1)
cl_int CL_API_CALL clEnqueueWriteBufferRect(
    cl_command_queue command_queue,
    cl_mem buffer,
    cl_bool blocking_write,
    const size_t * buffer_origin,
    const size_t * host_origin,
    const size_t * region,
    size_t buffer_row_pitch,
    size_t buffer_slice_pitch,
    size_t host_row_pitch,
    size_t host_slice_pitch,
    const void * ptr,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueWriteBufferRect);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, buffer, blocking_write, buffer_origin, host_origin, region, buffer_row_pitch, buffer_slice_pitch, host_row_pitch, host_slice_pitch, ptr, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_2)
cl_int CL_API_CALL clEnqueueFillBuffer(
    cl_command_queue command_queue,
    cl_mem buffer,
    const void * pattern,
    size_t pattern_size,
    size_t offset,
    size_t size,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueFillBuffer);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, buffer, pattern, pattern_size, offset, size, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clEnqueueCopyBuffer(
    cl_command_queue command_queue,
    cl_mem src_buffer,
    cl_mem dst_buffer,
    size_t src_offset,
    size_t dst_offset,
    size_t size,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueCopyBuffer);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, src_buffer, dst_buffer, src_offset, dst_offset, size, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_1)
cl_int CL_API_CALL clEnqueueCopyBufferRect(
    cl_command_queue command_queue,
    cl_mem src_buffer,
    cl_mem dst_buffer,
    const size_t * src_origin,
    const size_t * dst_origin,
    const size_t * region,
    size_t src_row_pitch,
    size_t src_slice_pitch,
    size_t dst_row_pitch,
    size_t dst_slice_pitch,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueCopyBufferRect);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, src_buffer, dst_buffer, src_origin, dst_origin, region, src_row_pitch, src_slice_pitch, dst_row_pitch, dst_slice_pitch, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clEnqueueReadImage(
    cl_command_queue command_queue,
    cl_mem image,
    cl_bool blocking_read,
    const size_t * origin,
    const size_t * region,
    size_t row_pitch,
    size_t slice_pitch,
    void * ptr,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueReadImage);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, image, blocking_read, origin, region, row_pitch, slice_pitch, ptr, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clEnqueueWriteImage(
    cl_command_queue command_queue,
    cl_mem image,
    cl_bool blocking_write,
    const size_t * origin,
    const size_t * region,
    size_t input_row_pitch,
    size_t input_slice_pitch,
    const void * ptr,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueWriteImage);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, image, blocking_write, origin, region, input_row_pitch, input_slice_pitch, ptr, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_2)
cl_int CL_API_CALL clEnqueueFillImage(
    cl_command_queue command_queue,
    cl_mem image,
    const void * fill_color,
    const size_t * origin,
    const size_t * region,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueFillImage);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, image, fill_color, origin, region, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clEnqueueCopyImage(
    cl_command_queue command_queue,
    cl_mem src_image,
    cl_mem dst_image,
    const size_t * src_origin,
    const size_t * dst_origin,
    const size_t * region,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueCopyImage);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, src_image, dst_image, src_origin, dst_origin, region, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clEnqueueCopyImageToBuffer(
    cl_command_queue command_queue,
    cl_mem src_image,
    cl_mem dst_buffer,
    const size_t * src_origin,
    const size_t * region,
    size_t dst_offset,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueCopyImageToBuffer);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, src_image, dst_buffer, src_origin, region, dst_offset, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clEnqueueCopyBufferToImage(
    cl_command_queue command_queue,
    cl_mem src_buffer,
    cl_mem dst_image,
    size_t src_offset,
    const size_t * dst_origin,
    const size_t * region,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueCopyBufferToImage);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, src_buffer, dst_image, src_offset, dst_origin, region, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_0)
void * CL_API_CALL clEnqueueMapBuffer(
    cl_command_queue command_queue,
    cl_mem buffer,
    cl_bool blocking_map,
    cl_map_flags map_flags,
    size_t offset,
    size_t size,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clEnqueueMapBuffer);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(command_queue, buffer, blocking_map, map_flags, offset, size, num_events_in_wait_list, event_wait_list, event, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_0)
void * CL_API_CALL clEnqueueMapImage(
    cl_command_queue command_queue,
    cl_mem image,
    cl_bool blocking_map,
    cl_map_flags map_flags,
    const size_t * origin,
    const size_t * region,
    size_t * image_row_pitch,
    size_t * image_slice_pitch,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clEnqueueMapImage);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(command_queue, image, blocking_map, map_flags, origin, region, image_row_pitch, image_slice_pitch, num_events_in_wait_list, event_wait_list, event, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clEnqueueUnmapMemObject(
    cl_command_queue command_queue,
    cl_mem memobj,
    void * mapped_ptr,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueUnmapMemObject);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, memobj, mapped_ptr, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_2)
cl_int CL_API_CALL clEnqueueMigrateMemObjects(
    cl_command_queue command_queue,
    cl_uint num_mem_objects,
    const cl_mem * mem_objects,
    cl_mem_migration_flags flags,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueMigrateMemObjects);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, num_mem_objects, mem_objects, flags, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clEnqueueNDRangeKernel(
    cl_command_queue command_queue,
    cl_kernel kernel,
    cl_uint work_dim,
    const size_t * global_work_offset,
    const size_t * global_work_size,
    const size_t * local_work_size,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueNDRangeKernel);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, kernel, work_dim, global_work_offset, global_work_size, local_work_size, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_0)
cl_int CL_API_CALL clEnqueueNativeKernel(
    cl_command_queue command_queue,
    void (CL_CALLBACK * user_func)(void *),
    void * args,
    size_t cb_args,
    cl_uint num_mem_objects,
    const cl_mem * mem_list,
    const void ** args_mem_loc,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueNativeKernel);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, user_func, args, cb_args, num_mem_objects, mem_list, args_mem_loc, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_2)
cl_int CL_API_CALL clEnqueueMarkerWithWaitList(
    cl_command_queue command_queue,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueMarkerWithWaitList);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_2)
cl_int CL_API_CALL clEnqueueBarrierWithWaitList(
    cl_command_queue command_queue,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueBarrierWithWaitList);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_2_0)
cl_int CL_API_CALL clEnqueueSVMFree(
    cl_command_queue command_queue,
    cl_uint num_svm_pointers,
    void * svm_pointers[],
    void (CL_CALLBACK * pfn_free_func)(cl_command_queue queue, cl_uint num_svm_pointers, void * svm_pointers[], void * user_data),
    void * user_data,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueSVMFree);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, num_svm_pointers, svm_pointers, pfn_free_func, user_data, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_2_0)
cl_int CL_API_CALL clEnqueueSVMMemcpy(
    cl_command_queue command_queue,
    cl_bool blocking_copy,
    void * dst_ptr,
    const void * src_ptr,
    size_t size,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueSVMMemcpy);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, blocking_copy, dst_ptr, src_ptr, size, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_2_0)
cl_int CL_API_CALL clEnqueueSVMMemFill(
    cl_command_queue command_queue,
    void * svm_ptr,
    const void * pattern,
    size_t pattern_size,
    size_t size,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueSVMMemFill);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, svm_ptr, pattern, pattern_size, size, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_2_0)
cl_int CL_API_CALL clEnqueueSVMMap(
    cl_command_queue command_queue,
    cl_bool blocking_map,
    cl_map_flags flags,
    void * svm_ptr,
    size_t size,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueSVMMap);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, blocking_map, flags, svm_ptr, size, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_2_0)
cl_int CL_API_CALL clEnqueueSVMUnmap(
    cl_command_queue command_queue,
    void * svm_ptr,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueSVMUnmap);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, svm_ptr, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_2_1)
cl_int CL_API_CALL clEnqueueSVMMigrateMem(
    cl_command_queue command_queue,
    cl_uint num_svm_pointers,
    const void ** svm_pointers,
    const size_t * sizes,
    cl_mem_migration_flags flags,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueSVMMigrateMem);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, num_svm_pointers, svm_pointers, sizes, flags, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_2)
void * CL_API_CALL clGetExtensionFunctionAddressForPlatform(
    cl_platform_id platform,
    const char * func_name)
{
    CL_RESOLVE(clGetExtensionFunctionAddressForPlatform);
    if (fp == nullptr) {
        return nullptr;
    }
    return fp(platform, func_name);
}
#endif

#if defined(CL_VERSION_1_0) && defined(CL_USE_DEPRECATED_OPENCL_1_0_APIS)
cl_int CL_API_CALL clSetCommandQueueProperty(
    cl_command_queue command_queue,
    cl_command_queue_properties properties,
    cl_bool enable,
    cl_command_queue_properties * old_properties)
{
    CL_RESOLVE(clSetCommandQueueProperty);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, properties, enable, old_properties);
}
#endif

#if defined(CL_VERSION_1_1)
cl_mem CL_API_CALL clCreateImage2D(
    cl_context context,
    cl_mem_flags flags,
    const cl_image_format * image_format,
    size_t image_width,
    size_t image_height,
    size_t image_row_pitch,
    void * host_ptr,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreateImage2D);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, flags, image_format, image_width, image_height, image_row_pitch, host_ptr, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_1)
cl_mem CL_API_CALL clCreateImage3D(
    cl_context context,
    cl_mem_flags flags,
    const cl_image_format * image_format,
    size_t image_width,
    size_t image_height,
    size_t image_depth,
    size_t image_row_pitch,
    size_t image_slice_pitch,
    void * host_ptr,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreateImage3D);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, flags, image_format, image_width, image_height, image_depth, image_row_pitch, image_slice_pitch, host_ptr, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_1)
cl_int CL_API_CALL clEnqueueMarker(
    cl_command_queue command_queue,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueMarker);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, event);
}
#endif

#if defined(CL_VERSION_1_1)
cl_int CL_API_CALL clEnqueueWaitForEvents(
    cl_command_queue command_queue,
    cl_uint num_events,
    const cl_event * event_list)
{
    CL_RESOLVE(clEnqueueWaitForEvents);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, num_events, event_list);
}
#endif

#if defined(CL_VERSION_1_1)
cl_int CL_API_CALL clEnqueueBarrier(
    cl_command_queue command_queue)
{
    CL_RESOLVE(clEnqueueBarrier);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue);
}
#endif

#if defined(CL_VERSION_1_1)
cl_int CL_API_CALL clUnloadCompiler(
    void)
{
    CL_RESOLVE(clUnloadCompiler);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp();
}
#endif

#if defined(CL_VERSION_1_1)
void * CL_API_CALL clGetExtensionFunctionAddress(
    const char * func_name)
{
    CL_RESOLVE(clGetExtensionFunctionAddress);
    if (fp == nullptr) {
        return nullptr;
    }
    return fp(func_name);
}
#endif

#if defined(CL_VERSION_1_2)
cl_command_queue CL_API_CALL clCreateCommandQueue(
    cl_context context,
    cl_device_id device,
    cl_command_queue_properties properties,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreateCommandQueue);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, device, properties, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_2)
cl_sampler CL_API_CALL clCreateSampler(
    cl_context context,
    cl_bool normalized_coords,
    cl_addressing_mode addressing_mode,
    cl_filter_mode filter_mode,
    cl_int * errcode_ret)
{
    CL_RESOLVE(clCreateSampler);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, normalized_coords, addressing_mode, filter_mode, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_2)
cl_int CL_API_CALL clEnqueueTask(
    cl_command_queue command_queue,
    cl_kernel kernel,
    cl_uint num_events_in_wait_list,
    const cl_event * event_wait_list,
    cl_event * event)
{
    CL_RESOLVE(clEnqueueTask);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, kernel, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_0) && !defined(CL_NO_ICD_DISPATCH_EXTENSION_PROTOTYPES)
cl_mem CL_API_CALL clCreateFromGLBuffer(
    cl_context context,
    cl_mem_flags flags,
    cl_GLuint bufobj,
    cl_int* errcode_ret)
{
    CL_RESOLVE(clCreateFromGLBuffer);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, flags, bufobj, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_2) && !defined(CL_NO_ICD_DISPATCH_EXTENSION_PROTOTYPES)
cl_mem CL_API_CALL clCreateFromGLTexture(
    cl_context context,
    cl_mem_flags flags,
    cl_GLenum target,
    cl_GLint miplevel,
    cl_GLuint texture,
    cl_int* errcode_ret)
{
    CL_RESOLVE(clCreateFromGLTexture);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, flags, target, miplevel, texture, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_0) && !defined(CL_NO_ICD_DISPATCH_EXTENSION_PROTOTYPES)
cl_mem CL_API_CALL clCreateFromGLRenderbuffer(
    cl_context context,
    cl_mem_flags flags,
    cl_GLuint renderbuffer,
    cl_int* errcode_ret)
{
    CL_RESOLVE(clCreateFromGLRenderbuffer);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, flags, renderbuffer, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_0) && !defined(CL_NO_ICD_DISPATCH_EXTENSION_PROTOTYPES)
cl_int CL_API_CALL clGetGLObjectInfo(
    cl_mem memobj,
    cl_gl_object_type* gl_object_type,
    cl_GLuint* gl_object_name)
{
    CL_RESOLVE(clGetGLObjectInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(memobj, gl_object_type, gl_object_name);
}
#endif

#if defined(CL_VERSION_1_0) && !defined(CL_NO_ICD_DISPATCH_EXTENSION_PROTOTYPES)
cl_int CL_API_CALL clGetGLTextureInfo(
    cl_mem memobj,
    cl_gl_texture_info param_name,
    size_t param_value_size,
    void* param_value,
    size_t* param_value_size_ret)
{
    CL_RESOLVE(clGetGLTextureInfo);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(memobj, param_name, param_value_size, param_value, param_value_size_ret);
}
#endif

#if defined(CL_VERSION_1_0) && !defined(CL_NO_ICD_DISPATCH_EXTENSION_PROTOTYPES)
cl_int CL_API_CALL clEnqueueAcquireGLObjects(
    cl_command_queue command_queue,
    cl_uint num_objects,
    const cl_mem* mem_objects,
    cl_uint num_events_in_wait_list,
    const cl_event* event_wait_list,
    cl_event* event)
{
    CL_RESOLVE(clEnqueueAcquireGLObjects);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, num_objects, mem_objects, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_0) && !defined(CL_NO_ICD_DISPATCH_EXTENSION_PROTOTYPES)
cl_int CL_API_CALL clEnqueueReleaseGLObjects(
    cl_command_queue command_queue,
    cl_uint num_objects,
    const cl_mem* mem_objects,
    cl_uint num_events_in_wait_list,
    const cl_event* event_wait_list,
    cl_event* event)
{
    CL_RESOLVE(clEnqueueReleaseGLObjects);
    if (fp == nullptr) {
        return CL_INVALID_OPERATION;
    }
    return fp(command_queue, num_objects, mem_objects, num_events_in_wait_list, event_wait_list, event);
}
#endif

#if defined(CL_VERSION_1_1) && !defined(CL_NO_ICD_DISPATCH_EXTENSION_PROTOTYPES)
cl_mem CL_API_CALL clCreateFromGLTexture2D(
    cl_context context,
    cl_mem_flags flags,
    cl_GLenum target,
    cl_GLint miplevel,
    cl_GLuint texture,
    cl_int* errcode_ret)
{
    CL_RESOLVE(clCreateFromGLTexture2D);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, flags, target, miplevel, texture, errcode_ret);
}
#endif

#if defined(CL_VERSION_1_1) && !defined(CL_NO_ICD_DISPATCH_EXTENSION_PROTOTYPES)
cl_mem CL_API_CALL clCreateFromGLTexture3D(
    cl_context context,
    cl_mem_flags flags,
    cl_GLenum target,
    cl_GLint miplevel,
    cl_GLuint texture,
    cl_int* errcode_ret)
{
    CL_RESOLVE(clCreateFromGLTexture3D);
    if (fp == nullptr) {
        if (errcode_ret != nullptr) {
            *errcode_ret = CL_INVALID_OPERATION;
        }
        return nullptr;
    }
    return fp(context, flags, target, miplevel, texture, errcode_ret);
}
#endif

} // extern "C"

#undef CL_RESOLVE
