#!/usr/bin/env python3
"""Generate typed C trampolines from the checked-in Khronos core declarations.

No compiler or OpenCL runtime is invoked. Run from any working directory.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
DECLARATION = re.compile(
    r'extern\s+CL_API_ENTRY\s+(?:CL_API_PREFIX__\w+\s+)?'
    r'(.*?)\s+CL_API_CALL\s+(cl\w+)\s*\((.*?)\)\s*'
    r'(CL_API_SUFFIX__\w+)\s*;', re.S)

PREAMBLE = '''// Generated by tools/generate_cl_symbols.py from CL/cl.h and CL/cl_gl.h.
// Keep callback types, C linkage and CL_API_CALL exactly as declared there.
#include "cl_symbols.h"

#include <string>
#include <vector>

namespace au {
namespace gpu {

CLSymbols& CLSymbols::instance()
{
    static CLSymbols instance;
    return instance;
}

bool CLSymbols::isLoaded() noexcept
{
    try {
        return instance().mLoaded;
    } catch (...) {
        return false;
    }
}

CLSymbols::CLSymbols()
{
    try {
        const std::vector<std::string> paths = {
#if AU_OS_WINDOWS
            "OpenCL.dll", "OpenCL64.dll", "OpenCL32.dll"
#elif AU_OS_APPLE
            "/System/Library/Frameworks/OpenCL.framework/OpenCL"
#elif AU_OS_ANDROID
            "libOpenCL.so",
            "/vendor/lib64/libOpenCL.so", "/system/vendor/lib64/libOpenCL.so", "/system/lib64/libOpenCL.so",
            "/vendor/lib/libOpenCL.so", "/system/vendor/lib/libOpenCL.so", "/system/lib/libOpenCL.so"
#elif AU_OS_LINUX
            "libOpenCL.so.1", "libOpenCL.so",
            "/usr/lib/x86_64-linux-gnu/libOpenCL.so.1", "/usr/lib/x86_64-linux-gnu/libOpenCL.so",
            "/usr/lib/libOpenCL.so.1", "/usr/lib/libOpenCL.so", "/usr/lib64/libOpenCL.so.1", "/usr/lib64/libOpenCL.so"
#else
            "libOpenCL.so", "OpenCL.dll"
#endif
        };
        mLoaded = (mLib.load(paths) == sys::XDLib::kSuccess);
    } catch (...) {
        // Path allocation/loading failed. Calls report unavailable OpenCL
        // through their return values, rather than terminating the process.
        mLoaded = false;
    }
}

} // namespace gpu
} // namespace au

// Function-local static initialization publishes each pointer once, safely
// across threads. A missing pointer is cached too. Steady-state dispatch has
// no name lookup, container allocation or XDLib mutex acquisition.
#define CL_RESOLVE(name) \\
    static const auto fp = ::au::gpu::CLSymbols::get<decltype(::name)>(#name)

namespace {
#ifdef CL_PLATFORM_NOT_FOUND_KHR
constexpr cl_int kPlatformNotFound = CL_PLATFORM_NOT_FOUND_KHR;
#else
// Apple SDK headers omit the cl_khr_icd error macro; Khronos assigns -1001.
constexpr cl_int kPlatformNotFound = -1001;
#endif
} // anonymous namespace

// Unavailable core entry points return CL_INVALID_OPERATION. Handle/mapping
// creators also set errcode_ret when supplied. Extension queries return null;
// clSVMFree has no error return and becomes a no-op if its symbol is absent.
extern "C" {

'''


def parameters(arguments):
    """Split commas only outside callback signatures and extract argument names."""
    arguments = re.sub(r'\s+', ' ', arguments).strip()
    if arguments in ('', 'void'):
        return arguments, []
    parts, start, depth = [], 0, 0
    for index, char in enumerate(arguments):
        if char == '(':
            depth += 1
        elif char == ')':
            depth -= 1
        elif char == ',' and depth == 0:
            parts.append(arguments[start:index].strip())
            start = index + 1
    parts.append(arguments[start:].strip())
    names = []
    for part in parts:
        callback = re.search(r'\(CL_CALLBACK\s*\*\s*(\w+)\)', part)
        if callback:
            names.append(callback.group(1))
        else:
            name = re.search(r'(\w+)\s*(?:\[[^\]]*\])?$', part)
            if name is None:
                raise ValueError(f'Unnamed parameter: {part}')
            names.append(name.group(1))
    return ',\n    '.join(parts), names


def generate():
    text = (ROOT / 'CL/cl.h').read_text()
    functions = DECLARATION.findall(text)
    assert len(functions) == 114, 'Review generator when replacing Khronos headers'
    # CLHPP also exposes the standard OpenGL-sharing entry points. Vendor/KHR
    # suffixed extensions are queried through the platform extension resolver.
    gl_functions = [entry for entry in DECLARATION.findall((ROOT / 'CL/cl_gl.h').read_text())
                    if not entry[1].endswith(('KHR', 'INTEL', 'EXT'))]
    assert len(gl_functions) == 9
    gl_names = {entry[1] for entry in gl_functions}
    functions += gl_functions
    assert len({name for _, name, _, _ in functions}) == len(functions)
    blocks = [PREAMBLE]
    for result, name, arguments, suffix in functions:
        result = ' '.join(result.split())
        assert result in {'cl_int', 'cl_context', 'cl_command_queue', 'cl_mem',
                          'cl_sampler', 'cl_program', 'cl_kernel', 'cl_event',
                          'void *', 'void'}
        params, names = parameters(arguments)
        version = re.search(r'VERSION_(\d+)_(\d+)', suffix)
        assert version
        guard = f'defined(CL_VERSION_{version[1]}_{version[2]})'
        if name == 'clSetCommandQueueProperty':
            guard += ' && defined(CL_USE_DEPRECATED_OPENCL_1_0_APIS)'
        if name in gl_names:
            guard += ' && !defined(CL_NO_ICD_DISPATCH_EXTENSION_PROTOTYPES)'
        body = [f'#if {guard}',
                f'{result} CL_API_CALL {name}(\n    {params})', '{',
                f'    CL_RESOLVE({name});', '    if (fp == nullptr) {']
        if 'errcode_ret' in names:
            body += ['        if (errcode_ret != nullptr) {',
                     '            *errcode_ret = CL_INVALID_OPERATION;', '        }']
        if name == 'clGetPlatformIDs':
            body += ['        if (num_platforms != nullptr) {',
                     '            *num_platforms = 0;', '        }',
                     '        return kPlatformNotFound;']
        elif result == 'cl_int':
            body += ['        return CL_INVALID_OPERATION;']
        elif result == 'void':
            body += ['        return;']
        else:
            body += ['        return nullptr;']
        body += ['    }']
        call = f'fp({", ".join(names)})'
        body += [f'    {call};' if result == 'void' else f'    return {call};',
                 '}', '#endif', '']
        blocks.append('\n'.join(body) + '\n')
    blocks.append('} // extern "C"\n\n#undef CL_RESOLVE\n')
    return ''.join(blocks)


if __name__ == '__main__':
    output = ROOT / 'cl_symbols.cpp'
    output.write_text(generate())
    print(f'{output}: 114 guarded core trampolines and 9 OpenGL-sharing trampolines')
